export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: "cattegory/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "cattegory/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "cattegory/FETCH_CATEGORIES_FAILED",
};
